Server/skeleton
Nahagos/nahagos pull request #2
Opened 2024-12-01 14:42 UTC by mechina-19

2024-12-01 14:50 UTC, olivecylinder requested changes

2024-12-01 14:50 UTC, olivecylinder commented on server/__pycache__/server.cpython-312.pyc
should not be committed, add a gitignore

2024-12-01 14:50 UTC, olivecylinder commented on server/server.py
> +
remove or uncomment?

2024-12-01 14:50 UTC, olivecylinder commented on server/server.py
> +    #waiting_passengers.append(station_id, bus_id))
remove or uncomment?

2024-12-01 14:50 UTC, olivecylinder commented on server/server.py
> +     # else: return {"status": "Not up to date", "changes": []}
remove or uncomment? no return value

2024-12-01 14:50 UTC, olivecylinder commented on server/server.py
> +    return {"message", "200 OK"}
consider a unified login for both types? frontend (@number10mechina) says it's one screen

2024-12-01 14:50 UTC, olivecylinder commented on server/server.py
> +    return {"message", "200 OK"}
talk with frontend about a schema for the login API, it should return some user data as well

2024-12-01 14:51 UTC, olivecylinder commented
![](https://github.trello.services/images/mini-trello-icon.png) [server skeleton](https://trello.com/c/DQbRGwjq/13-server-skeleton)

2024-12-02 18:05 UTC, mechina-19 commented on server/__pycache__/server.cpython-312.pyc
Added gitignore

2024-12-02 18:09 UTC, mechina-19 commented on server/server.py
> +     # else: return {"status": "Not up to date", "changes": []}
Added a place holder return in the meantime

2024-12-02 18:11 UTC, mechina-19 commented on server/server.py
> +    return {"message", "200 OK"}
removed unnecessary functions

2024-12-02 18:13 UTC, mechina-19 commented on server/server.py
> +    #waiting_passengers.append(station_id, bus_id))
leave it like this for now, when we will have the queue we would uncomment

2024-12-02 18:15 UTC, mechina-19 commented on server/server.py
> +    return {"message", "200 OK"}
after thorough discussion it was decided it is unnecessary.

2024-12-02 18:22 UTC, olivecylinder requested changes

2024-12-02 18:22 UTC, olivecylinder commented on server/server.py
> +    cords: tuple
coordinates:)

2024-12-02 18:22 UTC, olivecylinder commented on server/server.py
> +
empty line between doc and code or not?

2024-12-02 18:22 UTC, olivecylinder commented on server/server.py
> +    # change the status of nahagos in this specific line
if a todo, add `TODO:`

2024-12-02 18:22 UTC, olivecylinder commented on server/server.py
> +    # change the status of nahagos in this specific line
if a todo, add `TODO:`

2024-12-02 18:22 UTC, olivecylinder commented on server/server.py
> +     # Compare last_updated_date to last date the station list was updated
if a todo, add `TODO:`

2024-12-02 18:22 UTC, olivecylinder commented on server/server.py
> +    return {"message", "200 OK"}
> it was decided it is unnecessary.

it was deemed*

2024-12-02 18:22 UTC, olivecylinder commented on server/server.py
> +
consistent spacing between functions
(reformat before committing?)

2024-12-12 15:41 UTC, olivecylinder approved these changes

2024-12-12 17:34 UTC, merged