Server/zip parse
Nahagos/nahagos pull request #4
Opened 2024-12-16 19:05 UTC by yael987

ask path to the file israel-public-transportation.zip, unzip it and then parse it to sql tables - each file is new table.

2024-12-18 16:19 UTC, goatOfLife requested changes

2024-12-18 16:19 UTC, goatOfLife commented on server/sql-parser.py
> +    zip_path = input("Enter path - zip file named israel-public-transportation: ")
probably mostly for testing. i would suggest adding that as console pararms, because i would guess the server dont want to write in the console every time...

2024-12-18 16:19 UTC, goatOfLife commented on server/sql-parser.py
> +
i would suggest to add some comments, just to explain a little bit how the cursor works. with asserting variables to string queries and such. or at least comment above the executemany line that every question mark is replaced by the according value.

2024-12-25 18:49 UTC, yael987 commented on server/sql-parser.py
> +    zip_path = input("Enter path - zip file named israel-public-transportation: ")
טופל

2024-12-25 18:49 UTC, yael987 commented on server/sql-parser.py
> +
בוצע+++

2024-12-26 17:25 UTC, olivecylinder commented on server/sql-parser.py
> +        line1 = file.readline().strip()
more descriptive name

2024-12-26 17:25 UTC, olivecylinder commented on server/sql-parser.py
> +        line1 = file.readline().strip()
more descriptive name

2024-12-26 17:59 UTC, olivecylinder requested changes

2024-12-26 17:59 UTC, olivecylinder commented on server/sql-parser.py
> +        line1 = file.readline().strip()
make descriptive name

2024-12-26 17:59 UTC, olivecylinder commented on server/sql-parser.py
> +        line1 = file.readline().strip()
also, maybe this should be the array already

2024-12-26 17:59 UTC, olivecylinder commented on server/sql-parser.py
> +            request_params.append(line)
could be replaces with list comprehension

2024-12-26 17:59 UTC, olivecylinder commented on server/sql-parser.py
> +        return False
this should be a python module kind-of, not a cli tool

2024-12-26 17:59 UTC, olivecylinder commented on server/sql-parser.py
> +    files_names = {
should be called `schema` then

2024-12-26 17:59 UTC, olivecylinder commented on server/sql-parser.py
> +        cursor.execute("CREATE TABLE IF NOT EXISTS " + file_name + " (" + ", ".join([var for var in columns]) + ")")
`[var for var in columns]` is equivalent to `columns`

2024-12-26 17:59 UTC, olivecylinder commented on server/sql-parser.py
> +def parse_file(cursor, path, file_name):
this is not only parsing, but also writing to the database

2024-12-26 18:50 UTC, yael987 commented on server/sql-parser.py
> +        cursor.execute("CREATE TABLE IF NOT EXISTS " + file_name + " (" + ", ".join([var for var in columns]) + ")")
fix

2024-12-26 18:51 UTC, yael987 commented on server/sql-parser.py
> +    files_names = {
not really matter

2024-12-26 18:53 UTC, yael987 commented on server/sql-parser.py
> +        return False
not rellevant in this versation

2024-12-26 18:54 UTC, yael987 commented on server/sql-parser.py
> +            request_params.append(line)
היה ניסיון, אבל יוצר בעיות עם הnull, ולכן השארתי ככה

2024-12-26 18:56 UTC, yael987 commented on server/sql-parser.py
> +        line1 = file.readline().strip()
השורה הראשונה הולכת לפח, אין בה שימוש בכל מקרה. בהמשך זה יותר רלוונטי ואכן מערך.

2024-12-26 18:56 UTC, yael987 commented on server/sql-parser.py
> +        line1 = file.readline().strip()
(השורה הזו היא רק כדי לקדם את הסמן בתוך הקובץ בשורה)

2024-12-26 18:58 UTC, yael987 commented on server/sql-parser.py
> +def parse_file(cursor, path, file_name):
טופל, אם כי היה מיותר

2024-12-30 17:39 UTC, olivecylinder commented
@yael987 please amend the last commit with a descriptive commit message

2024-12-30 17:41 UTC, olivecylinder commented on server/sql-parser.py
> +        line1 = file.readline().strip()
> השורה הראשונה הולכת לפח, אין בה שימוש בכל מקרה. בהמשך זה יותר רלוונטי ואכן מערך.

it's used in the line right after
also - mark as resolved only if code was changed

2024-12-30 17:43 UTC, olivecylinder commented on server/sql-parser.py
> +            request_params.append(line)
```python
request_params = [
    [var if var != '' else None for var in line.strip().split(",")]
    for line in file
]
```
is equivalent

2025-01-13 18:27 UTC, merged