Login page
Nahagos/nahagos pull request #6
Opened 2024-12-18 18:02 UTC by number10mechina

2024-12-18 18:16 UTC, goatOfLife requested changes

2024-12-18 18:16 UTC, goatOfLife commented on Nahagos/app/src/main/java/com/nahagos/nahagos/MainActivity.java
> +                Log.d("MainActivity", Boolean.toString(isCheckedGlobal));
before merge, should remove logging info

2024-12-18 18:16 UTC, goatOfLife commented on Nahagos/app/src/main/java/com/nahagos/nahagos/MainActivity.java
> +import java.net.URL;
i believe some of these imports are not used here, and were here before you built Networks.java and ServerAPI. if true, please delete.

2024-12-18 18:16 UTC, goatOfLife commented on Nahagos/app/src/main/java/com/nahagos/nahagos/Networks.java
> +            Log.d(TAG, "Response Code: " + responseCode);
again, although great for testing, logging should be removed before merge.

2024-12-18 18:16 UTC, goatOfLife commented on Nahagos/app/src/main/java/com/nahagos/nahagos/ServerAPI.java
> +    public void driverLogin(String username, String password, String id)
Might want to validate we don't send false ids to the server, so if a driver tries to log in with id "@$%$#@" it shouldn't send anything to the server.

2024-12-18 18:16 UTC, goatOfLife commented on Nahagos/app/src/main/res/values/strings.xml
> +    <string name="invalid_password">Password must be >5 characters</string>
is it constant? might be a good idea to change it to a variable, the minimum length of password, for future changes. Not that critical.

2024-12-23 17:41 UTC, number10mechina commented on Nahagos/app/src/main/java/com/nahagos/nahagos/Networks.java
> +            Log.d(TAG, "Response Code: " + responseCode);
relevant for the next developers, theyll need to implement parser for http coming requests

2024-12-23 17:43 UTC, number10mechina commented on Nahagos/app/src/main/java/com/nahagos/nahagos/ServerAPI.java
> +    public void driverLogin(String username, String password, String id)
relevent for the next developers & the server response - both not implemented

2024-12-23 17:45 UTC, number10mechina commented on Nahagos/app/src/main/java/com/nahagos/nahagos/MainActivity.java
> +import java.net.URL;
ok!

2024-12-23 17:45 UTC, number10mechina commented on Nahagos/app/src/main/java/com/nahagos/nahagos/MainActivity.java
> +                Log.d("MainActivity", Boolean.toString(isCheckedGlobal));
ok!

2024-12-23 17:46 UTC, number10mechina commented on Nahagos/app/src/main/res/values/strings.xml
> +    <string name="invalid_password">Password must be >5 characters</string>
in the feature features

2024-12-23 18:16 UTC, goatOfLife commented on Nahagos/app/src/main/java/com/nahagos/nahagos/MainActivity.java
> +                Log.d("MainActivity", Boolean.toString(isCheckedGlobal));
@number10mechina removed irrelevant logging, but some are still relevant for debugging later.

2024-12-23 18:17 UTC, goatOfLife approved these changes

2024-12-23 18:24 UTC, merged